### ISSUE TITLE
Potential energy

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework7G2#13]
Is this the the potential energy function for the Na4Cl4 cluster that we are going to use for it optimization?
![Screenshot from 2023-11-26 22-12-51](https://github.com/ubsuny/23-Homework7G1/assets/143649367/6c7c3440-661c-470c-a453-b43087114c6d)

**Comment by s4il3sh** [comment]
Yes.

**Comment by tirthbha** [comment]
@s4il3sh Did you use this formula?

**Comment by s4il3sh** [comment]
No. Did you?
