### ISSUE TITLE
How to initialize the task to find equilibrium configuration.

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework7G2#20]
Hi all, 
I am having confusion about the position selection for different configuration of tetramers given in paper? I appreciate if anyone could explain the value of position to be used for different configuration for initiation.

**Comment by AhmedCode99** [comment]
Dr. Tim said: There were two approaches to this problem. You could try to initialize the configurations randomly and wait until the solutions in the paper are located. Alternatively, you could initialize the positions close to the configurations in the paper and let the minimization run.
