### ISSUE TITLE
Anyone started working on the homework problems?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework7G2#24]

**Comment by tirthbha** [comment]
@s4il3sh Yes, do you have any questions?

**Comment by tirthbha** [comment]
Yes, I used the same values.
Did you find any issues with those values?
@s4il3sh

**Comment by yasmensarhan27** [comment]
yes 
I'm working on the 1st 2 configurations
the cubic and the pentagon

**Comment by s4il3sh** [comment]
> Yes, I used the same values. Did you find any issues with those values? @s4il3sh

@tirthbha Are we supposed to use the formula given in the paper to calculate potential energy?

**Comment by AhmedCode99** [comment]
yeah, i did all 7 configs
