### ISSUE TITLE
Unit Testing Action Always Fails

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework7G2#52]
Your unit testing action always fails because it attempts to run a nonexistant File named tests.py https://github.com/ubsuny/23-Homework7G2/blob/dd8eb5b5f328ad947ecca1edeb38c96e8dac04f8/.github/workflows/Unittesting.yml#L21 so I removed this statement in this pull request (https://github.com/ubsuny/23-Homework7G2/pull/50) since the unit testing is unnecessary for this project. Please look it over and see if you agree @AhmedCode99

**Comment by yasmensarhan27** [comment]
it is unnecessary to do the unit testing

**Comment by WildJimmy** [comment]
True, but then I still feel like it's a good idea to at least get rid of the run action so you don't get a unit test action failed notification for every pull request. Or maybe the file should just be deleted altogether if that's preferable

**Comment by AhmedCode99** [comment]
you are right jimmy
