### ISSUE TITLE
Saddle points

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G2#6]
what are saddle points?

**Comment by AhmedCode99** [comment]
For a multivariate function, a saddle point occurs when the first partial derivatives are zero, indicating a critical point. However, the second partial derivatives at this point show a mix of positive and negative values, suggesting that the function neither strictly increases nor decreases along all directions. This property distinguishes a saddle point from local extrema.

**Comment by AhmedCode99** [comment]
https://en.m.wikipedia.org/wiki/Saddle_point
