### ISSUE TITLE
Figure 4. seven configurations

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G2#8]
FYI
![image](https://github.com/ubsuny/23-Homework7G2/assets/143649458/f3f66c60-cf4e-4c33-88ef-63bb8762d135)
Fig. 4. The lowest energy configurations found for the cluster size of four
ion pairs along with their respective binding energies ~eV/ion pair!.

**Comment by s4il3sh** [comment]
Did you find out, what are the names of configurations?

**Comment by tirthbha** [comment]
I think the given configurations have the following names:
Cube
Planar Square
Planar Rectangle
Rhombus
Tetrahedron
Planar V-shape, Not sure
Linear

**Comment by reshnashrestha** [comment]
How did you find this out ? 
is there anything we should follow for names?

**Comment by reshnashrestha** [comment]
Okay.

**Comment by s4il3sh** [comment]
> I think the given configurations have the following names: Cube Planar Square Planar Rectangle Rhombus Tetrahedron Planar V-shape, Not sure Linear

second one doesn't look like square planar.
